- hosts: webservers
  become: true

  vars:
    apache_user: www-data
    apache_group: www-data

  vars_prompt:
    - name: "release_version_to_deploy"
      prompt: "Release version to deploy (input tag)"
      private: no

  pre_tasks:
    - name: deploy_app
      debug: msg="Start deploy_app playbook"

  tasks:
    - name: updates a server
      apt:
        update_cache: yes
    - name: install packages
      apt:
        pkg:
          - git
          - acl
        state: present
        update_cache: yes
    - name: Create a directory versions
      file:
        path: "{{ path }}/laravel/versions/"
        state: directory
        mode: "0755"
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"
    - name: Deploy laravel | clone repository
      git:
        repo: "https://{{ git_repo_user | urlencode }}:{{ git_repo_password | urlencode }}@{{ git_repo_url }}"
        dest: "{{ path }}/laravel/versions/app-{{ release_version_to_deploy }}"
        version: "tags/{{ release_version_to_deploy }}"
        recursive: yes
      become_user: "{{ apache_user }}"
      tags:
        - deploy_laravel_git
    - name: Check permissions
      file:
        path: "{{ path }}/laravel/versions/app-{{ release_version_to_deploy }}"
        state: directory
        mode: "0755"
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"
    - name: Copy file .env owner and permissions
      copy:
        src: "{{ env }}"
        dest: "{{ path }}/laravel/versions/app-{{ release_version_to_deploy }}/.env"
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"
        mode: "0644"

    - name: composer install dependencies
      composer:
        command: install
        working_dir: "{{ path }}/laravel/versions/app-{{ release_version_to_deploy }}"
    - name: Create current symlink
      file:
        src: "{{ path }}/laravel/versions/app-{{ release_version_to_deploy }}"
        dest: "{{ path }}/laravel/versions/current"
        state: link

  post_tasks:
    - name: deploy_app
      debug: msg="End deploy_app playbook"
